### ISSUE TITLE
ClassificationRequest.imageCropAndScaleOption = VNImageCropAndScleOption.centerCrop

### ISSUE THREAD

**Issue by kerinzeebart** [hanleyweng/CoreML-in-ARKit#1]
Can't compile code.
I get Type 'VNImageCropandScaleOption' has no member 'centerCrop' I added the inceptionV3Model model

**Comment by hanleyweng** [comment]
Hi @kerinzeebart , 
Which XCode 9 Beta are you using?

**Comment by hanleyweng** [comment]
It appears that: Xcode 9 beta 1 and Xcode 9 beta 2 - both use
"VNImageCropAndScaleOptionCenterCrop" instead of Xcode 9 beta 3's "VNImageCropAndScleOption.centerCrop"
changing to that should fix it. Again, this is all experimental beta code currently.
