### ISSUE TITLE
something wrong with inceptionv3.mlmodel

### ISSUE THREAD

**Issue by jbtxwd** [hanleyweng/CoreML-in-ARKit#3]
I already copy the inceptionv3.mlmodel into project.but when i click Inceptionv3.mlmodel,it shows "  Interface generation only available with valid target",which dont like the gif of yours.

**Comment by hanleyweng** [comment]
Hi jbtxwd,

That's interesting. Hmmm, sometimes Xcode takes a while to register the mlmodel file. I'd also try redownloading the mlmodel, just in case it got corrupted - perhaps run it across some basic CoreML tutorials / sample codes to make sure the mlmodel file is valid.

I'd also try toggling around with your iOS 11 beta versions, as well as your Xcode 9 beta versions. (This example was tested on iOS 11 beta 3 and Xcode 9 beta 3)

Let me know how it goes.

Update:
Ah it seems like a version of Xcode is having trouble with the drag and drop and "add the model by right click and selecting "Add files to project"" - may work.
src: https://stackoverflow.com/questions/45345873/why-is-inceptionv3-machine-learning-model-not-recognized-on-my-project
