### ISSUE TITLE
How is the Label move as i move the object?

### ISSUE THREAD

**Issue by yaalisri** [hanleyweng/CoreML-in-ARKit#8]
I tried running the project in iPhone 7 plus and it is working fine. I noticed as i move the object slowly, even the label moves. But in source code position updation of the node is not happening. Then how come, the text node is moving as i move the object slowly?

**Comment by hanleyweng** [comment]
Hmm. In this case, the Text Node shouldn't technically move when an object moves. If you have a gif / video to share that'd be helpful. I imagine it's a coincidental glitch on the ARKit side of things, as ARKit can take some time to initialize and get its bearings.
